### ISSUE TITLE
Full Stack Staking dApp Tutorial (Medium article) - Reward $1.5k (in $CCDs) [+ Video Tutorial Bonus] 

### ISSUE THREAD

**Issue by bogacyigitbasi** [Concordium/concordium-bounty-program#5]
- Implement a staking platform including smart contract, front-end, and documentation.
- Tutorial documentation must show all details of the implementation with brief descriptions. 
- Open-sourced Github repo
- Hosted on testnet and vercel app or GitHub pages
- You should use Concordium tools like [VSCode extension](https://marketplace.visualstudio.com/items?itemName=Concordium.concordium-smart-contracts),[ccd-js-gen](https://www.npmjs.com/package/@concordium/ccd-js-gen), [sc-tools](https://sctools.mainnet.concordium.software/)) if applicable
- If maintenance is required, the participant is responsible for 3 months.

**Comment by vlmoon99** [comment]
@bogacyigitbasi It's okay to do that with Dart/Flutter using my own SDK, Flutterchain: https://github.com/vlmoon99/flutterchain. I want to add Concordium to my SDK and create iOS, Android, and web apps using Dart/Flutter and Flutterchain, where I will have all the tools necessary to use Concordium.

**Comment by bogacyigitbasi** [comment]
@vlmoon99 even though it sounds like a nice idea to expand Concordium, we would like to have the tutorials highlighting official SDSs we have created and keep maintaining. Thank you for the suggestion, but this time I have to ask you to choose one of [these](https://developer.concordium.software/en/mainnet/net/guides/sdks-apis.html). Have a great day and let us know!

**Comment by AyyanNiazi** [comment]
@bogacyigitbasi I'd like to take this as well

**Comment by bogacyigitbasi** [comment]
Well, there has been no demand so far in months, and clearly no submissions. You have called dibs!  LFG 🚀

**Comment by amdonatusprince** [comment]
Hi Bogac, I indicated interest on working on this bounty sometime last week and we're already in the last step of the integration

**Comment by amdonatusprince** [comment]
Hi @bogacyigitbasi , I've sent our submission to your email for review and feedback. Thanks

**Comment by erasmus** [comment]
Any chance the code & tutorial could be shared here, too?
