### ISSUE TITLE
Full Stack Smart Contract Account Tutorial (Medium article) - Reward $2k (in $CCDs) [+ Video Tutorial Bonus] 

### ISSUE THREAD

**Issue by bogacyigitbasi** [Concordium/concordium-bounty-program#6]
- Create an example dApp showing [CIS-5](https://proposals.concordium.software/CIS/cis-5.html) standard smart contract, a front-end, and documentation.
- Tutorial documentation must show all details of the implementation with brief descriptions. 
- Open-sourced Github repo
- Hosted on testnet and vercel app or GitHub pages
- You should use Concordium tools like [VSCode extension](https://marketplace.visualstudio.com/items?itemName=Concordium.concordium-smart-contracts),[ccd-js-gen](https://www.npmjs.com/package/@concordium/ccd-js-gen), [sc-tools](https://sctools.mainnet.concordium.software/)) if applicable
- If maintenance is required, the participant is responsible for 3 months.

**Comment by BukiOffor** [comment]
This is quite interesting and I will be building on this bounty !!

**Comment by bogacyigitbasi** [comment]
Excellent! Looking forward to it!

**Comment by BukiOffor** [comment]
How is the submission going to work. Do I build on my personal repo or fork this repo and create a sub folder

**Comment by bogacyigitbasi** [comment]
You can start working in a public personal repo, we share a feedback channel through Discord or Telegram once you have something to share to get feedback or if you need anything. When its done you will create a PR under probably [dapp-examples](https://github.com/Concordium/concordium-dapp-examples) and we will merge your example after final change requests. 
Since this is a tutorial, there will be an article (maybe a video) attached to it, so ideally you should create the tutorial and share it before this merge step. I will discuss this topic with the DevRel team if they have another suggestion but until that time, this is good for submissions. Thank you!

**Comment by BukiOffor** [comment]
guys, I have the full dapp example  [here](https://github.com/BukiOffor/cis5-smart-contract-dapp.git) and the complete tutorial at  [part one](https://medium.com/@buki.offor/concordium-full-stack-smart-contract-account-tutorial-part-one-cdac8bcf0ff9) and  [part two](https://medium.com/@buki.offor/concordium-full-stack-smart-contract-account-tutorial-part-two-2aa6fb81f2b7) . This was exciting and I look forward to your feedback. Thank you

**Comment by bogacyigitbasi** [comment]
Great stuff! We will get back to you after reviewing these.

**Comment by bogacyigitbasi** [comment]
Could you please create a PR in [here](https://github.com/Concordium/concordium-dapp-examples) for the source code?

**Comment by BukiOffor** [comment]
okay, on it

**Comment by bogacyigitbasi** [comment]
@BukiOffor thank you for the great work here. I am glad to share that you have successfully finished this bounty!

**Comment by BukiOffor** [comment]
Thank you @bogacyigitbasi for all your help
